name: Obter Variáveis do Ambiente de Produção

on:
  push:
    branches:
      - main

jobs:
  obter-variaveis:
    runs-on: ubuntu-latest
    environment: 
      name: producao
    steps:
      - name: Verificar valores das variáveis
        run: |
          echo "O valor da variável PASSWORD é ${{ secrets.PASSWORD }} "
          echo "O valor da variável BANCO é ${{ secrets.BANCO }}"
